services:
  - type: web
    name: solar-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd summative/API && uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

